apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/memory-tier-high

namePrefix: flashapp-

commonLabels:
  app: flashapp

images:
  - name: openms-streamlit
    newName: ghcr.io/openms/flashapp
    newTag: latest

patches:
  - target:
      kind: IngressRoute
      name: streamlit-traefik
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: (Host(`flashapp.webapps.openms.de`) || Host(`flashapp.webapps.openms.org`)) && PathPrefix(`/`)
      - op: replace
        path: /spec/routes/0/services/0/name
        value: flashapp-streamlit
  - target:
      kind: Deployment
      name: streamlit
    patch: |
      - op: replace
        path: /spec/replicas
        value: 10
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "redis://flashapp-redis:6379/0"
  - target:
      kind: Deployment
      name: rq-worker
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "redis://flashapp-redis:6379/0"
